spring.application.name=turnos-api
server.port=8080

# conexion mariadb
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/reservas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:reservas_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# configuracion jpa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# broker mqtt
mqtt.broker.url=${MQTT_BROKER_URL:tcp://localhost:1883}
mqtt.topic=${MQTT_TOPIC:turnos/reservas}

# swagger ui y openapi
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
